# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12f53f38d130a6108cde5d65675b5fc28a87003757a2e54e6b04a3377a8c15c8d0f42bc85e2b827902209b8c4672f6bddf06d81be2da9474b9e2ec50c6e4b130

test:
  secret_key_base: bf7ee2df4fe5e5b7fabf4ef9e4813d3e956d018e2c13dbe3c09915a46ba99b15144689f7915e0ffcc337d17a47c519a79990e0210cecfee8eb03e571812b93eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
